SHELL := /usr/bin/env bash
.DEFAULT_GOAL := help

PYTHON ?= python3
NPM ?= npm
PORT ?= 8000
HOST ?= 127.0.0.1
GOVERNED_PYPI_TOOLS ?= agent-generator gitcopilot crewai
MATRIX_BUILDER_REPO ?= git+https://github.com/agent-matrix/matrix-builder.git
MATRIX_DESIGNER_REPO ?= git+https://github.com/ruslanmv/matrix-designer.git

.PHONY: help install install-node install-governed-tools build verify smoke design generate run clean

help:
	@echo "Contract Quest workflow targets"
	@echo ""
	@echo "  make install                Install local npm dependencies and attempt governed Python tool install"
	@echo "  make build                  Run ./build.sh all (design artifact validation + local verification)"
	@echo "  make verify                 Run ./build.sh verify"
	@echo "  make smoke                  Run npm smoke script"
	@echo "  make design                 Run ./build.sh design"
	@echo "  make generate               Run ./build.sh generate"
	@echo "  make run [PORT=8000]        Serve the created frontend app locally"
	@echo "  make clean                  Remove local caches generated by the workflow"
	@echo ""
	@echo "Set REQUIRE_GOVERNED_TOOLS=1 for strict GitPilot/Matrix Builder generation."

install: install-node install-governed-tools

install-node:
	@echo "==> Installing npm dependencies"
	@if [ -f package-lock.json ]; then \
		$(NPM) install; \
	else \
		$(NPM) install --package-lock=false; \
	fi

install-governed-tools:
	@echo "==> Attempting governed workflow Python tool install"
	@echo "    PyPI tools: $(GOVERNED_PYPI_TOOLS)"
	@for tool in $(GOVERNED_PYPI_TOOLS); do \
		echo "    Installing PyPI tool: $$tool"; \
		$(PYTHON) -m pip install "$$tool" || echo "WARNING: $$tool could not be installed from PyPI."; \
	done
	@echo "    Matrix Builder repo: $(MATRIX_BUILDER_REPO)"
	@$(PYTHON) -m pip install "$(MATRIX_BUILDER_REPO)" || { \
		echo "WARNING: Matrix Builder could not be installed from its repository."; \
	}
	@echo "    Matrix Designer repo: $(MATRIX_DESIGNER_REPO)"
	@$(PYTHON) -m pip install "$(MATRIX_DESIGNER_REPO)" || { \
		echo "WARNING: Matrix Designer could not be installed from its repository."; \
	}
	@echo "==> Governed Python tool install step complete"
	@echo "    If mb/mdesign/gitpilot are still unavailable, check network access and the repository URLs above."

build:
	@echo "==> Running governed build workflow"
	@./build.sh all

verify:
	@./build.sh verify

smoke:
	@$(NPM) run smoke

design:
	@./build.sh design

generate:
	@./build.sh generate

run:
	@echo "==> Serving Contract Quest at http://$(HOST):$(PORT)"
	@$(PYTHON) -m http.server "$(PORT)" --bind "$(HOST)" --directory frontend

clean:
	@echo "==> Removing local workflow caches"
	@rm -rf .mb .pytest_cache test-results playwright-report
