SHELL := /usr/bin/env bash
.DEFAULT_GOAL := help

PYTHON ?= python3
NPM ?= npm
PORT ?= 8000
HOST ?= 127.0.0.1
GOVERNED_PY_TOOLS ?= agent-generator gitcopilot crewai matrix-designer
GOVERNED_REQUIRED_CMDS ?= mdesign mb gitpilot
MATRIX_DESIGNER_REPO ?= https://github.com/agent-matrix/matrix-designer.git
MATRIX_DESIGNER_DIR ?= .tools/matrix-designer
MATRIX_BUILDER_REPO ?= https://github.com/agent-matrix/matrix-builder.git
MATRIX_BUILDER_DIR ?= .tools/matrix-builder

.PHONY: help install install-node install-governed-tools build verify smoke design generate run clean

help:
	@echo "Contract Quest workflow targets"
	@echo ""
	@echo "  make install                Install local npm dependencies and attempt governed Python tool install"
	@echo "  make build                  Run ./build.sh all (governed generation when tools exist; local fallback otherwise)"
	@echo "  make verify                 Run ./build.sh verify (checked-in static artifacts only)"
	@echo "  make smoke                  Run npm smoke script"
	@echo "  make design                 Run ./build.sh design"
	@echo "  make generate               Run ./build.sh generate"
	@echo "  make run [PORT=8000]        Serve the created frontend app locally"
	@echo "  make clean                  Remove local caches generated by the workflow"
	@echo ""
	@echo "Set WATSONX_API_KEY and WATSONX_PROJECT_ID before make build/generate for governed AI generation."
	@echo "By default make build falls back to checked-in artifact validation when governed tools are unavailable."
	@echo "Set REQUIRE_GOVERNED_TOOLS=1 to fail instead of using that fallback."

install: install-node install-governed-tools

install-node:
	@echo "==> Installing npm dependencies"
	@if [ -f package-lock.json ]; then \
		$(NPM) install; \
	else \
		$(NPM) install --package-lock=false; \
	fi

install-governed-tools:
	@echo "==> Attempting governed workflow Python tool install"
	@echo "    PyPI tools: $(GOVERNED_PY_TOOLS)"
	@echo "    Matrix Designer repo: $(MATRIX_DESIGNER_REPO)"
	@echo "    Matrix Builder repo: $(MATRIX_BUILDER_REPO)"
	@echo "    Required commands after install: $(GOVERNED_REQUIRED_CMDS)"
	@status=0; \
	for tool in $(GOVERNED_PY_TOOLS); do \
		$(PYTHON) -m pip install "$$tool" || status=$$?; \
	done; \
	if [ -d "$(MATRIX_DESIGNER_DIR)/.git" ]; then \
		echo "==> Updating Matrix Designer checkout"; \
		git -C "$(MATRIX_DESIGNER_DIR)" pull --ff-only || status=$$?; \
	else \
		echo "==> Cloning Matrix Designer"; \
		rm -rf "$(MATRIX_DESIGNER_DIR)"; \
		mkdir -p "$$(dirname "$(MATRIX_DESIGNER_DIR)")"; \
		git clone "$(MATRIX_DESIGNER_REPO)" "$(MATRIX_DESIGNER_DIR)" || status=$$?; \
	fi; \
	if [ -d "$(MATRIX_DESIGNER_DIR)" ]; then \
		$(PYTHON) -m pip install "$(MATRIX_DESIGNER_DIR)" || status=$$?; \
	fi; \
	if [ -d "$(MATRIX_BUILDER_DIR)/.git" ]; then \
		echo "==> Updating Matrix Builder checkout"; \
		git -C "$(MATRIX_BUILDER_DIR)" pull --ff-only || status=$$?; \
	else \
		echo "==> Cloning Matrix Builder"; \
		rm -rf "$(MATRIX_BUILDER_DIR)"; \
		mkdir -p "$$(dirname "$(MATRIX_BUILDER_DIR)")"; \
		git clone "$(MATRIX_BUILDER_REPO)" "$(MATRIX_BUILDER_DIR)" || status=$$?; \
	fi; \
	if [ -d "$(MATRIX_BUILDER_DIR)" ]; then \
		$(PYTHON) -m pip install "$(MATRIX_BUILDER_DIR)" || status=$$?; \
	fi; \
	for cmd in $(GOVERNED_REQUIRED_CMDS); do \
		command -v "$$cmd" >/dev/null 2>&1 || { echo "WARNING: required governed command not found: $$cmd"; status=1; }; \
	done; \
	if [ "$$status" -ne 0 ]; then \
		echo "WARNING: governed Python tools could not be installed in this environment."; \
		echo "         Local build/run targets still work with the checked-in static game."; \
		echo "         Re-run make install after network/tool issues are resolved for full generation."; \
	fi

build:
	@echo "==> Running governed build workflow"
	@./build.sh all

verify:
	@./build.sh verify

smoke:
	@$(NPM) run smoke

design:
	@./build.sh design

generate:
	@./build.sh generate

run:
	@echo "==> Serving Contract Quest at http://$(HOST):$(PORT)"
	@$(PYTHON) -m http.server "$(PORT)" --bind "$(HOST)" --directory frontend

clean:
	@echo "==> Removing local workflow caches"
	@rm -rf .mb .pytest_cache test-results playwright-report
