SHELL := /usr/bin/env bash
.DEFAULT_GOAL := help

PYTHON ?= python3
NPM ?= npm
PORT ?= 8000
HOST ?= 127.0.0.1
GOVERNED_PY_TOOLS ?= agent-generator gitcopilot crewai matrix-builder matrix-designer

.PHONY: help install install-node install-governed-tools build verify smoke design generate run clean

help:
	@echo "Contract Quest workflow targets"
	@echo ""
	@echo "  make install                Install local npm dependencies and attempt governed Python tool install"
	@echo "  make build                  Run ./build.sh all (design artifact validation + local verification)"
	@echo "  make verify                 Run ./build.sh verify"
	@echo "  make smoke                  Run npm smoke script"
	@echo "  make design                 Run ./build.sh design"
	@echo "  make generate               Run ./build.sh generate"
	@echo "  make run [PORT=8000]        Serve the created frontend app locally"
	@echo "  make clean                  Remove local caches generated by the workflow"
	@echo ""
	@echo "Set REQUIRE_GOVERNED_TOOLS=1 for strict GitPilot/Matrix Builder generation."

install: install-node install-governed-tools

install-node:
	@echo "==> Installing npm dependencies"
	@if [ -f package-lock.json ]; then \
		$(NPM) install; \
	else \
		$(NPM) install --package-lock=false; \
	fi

install-governed-tools:
	@echo "==> Attempting governed workflow Python tool install"
	@echo "    Tools: $(GOVERNED_PY_TOOLS)"
	@$(PYTHON) -m pip install $(GOVERNED_PY_TOOLS) || { \
		echo "WARNING: governed Python tools could not be installed in this environment."; \
		echo "         Local build/run targets still work with the checked-in static game."; \
		echo "         Re-run in a network-enabled environment for full mb/gitpilot generation."; \
	}

build:
	@echo "==> Running governed build workflow"
	@./build.sh all

verify:
	@./build.sh verify

smoke:
	@$(NPM) run smoke

design:
	@./build.sh design

generate:
	@./build.sh generate

run:
	@echo "==> Serving Contract Quest at http://$(HOST):$(PORT)"
	@$(PYTHON) -m http.server "$(PORT)" --bind "$(HOST)" --directory frontend

clean:
	@echo "==> Removing local workflow caches"
	@rm -rf .mb .pytest_cache test-results playwright-report
